{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sharecare.serviceAccountName" . }}
  labels:
{{ include "sharecare.labels" . | nindent 4 }}
{{- end -}}
