apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Charity
  template:
    metadata:
      labels:
        app: Charity
    spec: 
      containers:
      - name:  charity-deployment
        image: gcr.io/lloyds-hack-t1/charity_image:latest
        env:
        - name: DATABASE_HOST
          value: "35.246.56.176"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: charity
        - name: DATABASE_USERNAME
          value: postgres
        - name: DATABASE_PASSWORD
          value: q~+0x^'8/_D`h'nX
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: charity-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: Charity
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-resource
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
  spec:
    rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/charities"
          backend:
            service:
              name: charity-service
              port:
                number: 80
