apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Charity
  template:
    metadata:
      labels:
        app: Charity
    spec: 
      containers:
      - name:  charity-deployment
        image: gcr.io/lloyds-hack-t1/charity_image:latest
        env:
        - name: DATABASE_HOST
          value: 35.246.56.176
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass2
              key: charitydb
              optional: false
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass2
              key: username
              optional: false
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass2
              key: password
              optional: false
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: charity-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: Charity
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-resource-charity
  spec:
    ingressClassName: nginx
    rules:
    - http:
        paths:
        - pathType: Prefix
          path: /charities
          backend:
            service:
              name: charity-service
              port:
                number: 80
