apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Web
  template:
    metadata:
      labels:
        app: Web
    spec: 
      containers:
      - name:  web-deployment
        image: gcr.io/lloyds-hack-t1/web_image:latest
        env:
        - name: BASE_URL
          value: 34.142.119.162 
        - name: NUXT_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: Web
---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-resource
  spec:
    ingressClassName: nginx
    rules:
    - http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: web-service
              port:
                number: 80

