apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1 #this is the part we spin up/down number of pod we want to run
  selector: 
    matchLabels:
      app: web
  template:
    metadata: 
      labels:
        app: web
    spec:
  containers:
  - name:

---
apiVersion: 
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1 #this is the part we spin up/down number of pod we want to run
  selector: 
    matchLabels:
      app: web
  template:
    metadata: 
      labels:
        app: web
    spec:
  containers:
  - name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource #this name only accept lowercase
spec:
  replicas: 1 #this is the part we spin up/down number of pod we want to run
  selector: 
    matchLabels:
      app: web
  template:
    metadata: 
      labels:
        app: web
    spec:
  containers:
  - name: web